In [1]:
import numpy as np

In [2]:
x=[2,3,4,6]
y=np.array(x)

In [3]:
print(x, type(x))

[2, 3, 4, 6] <class 'list'>


In [4]:
print(y,type(y))

[2 3 4 6] <class 'numpy.ndarray'>


In [5]:
print(x[1:3])

[3, 4]


In [6]:
print(y[1:3])

[3 4]


In [7]:
print(x[[0,2]])

TypeError: list indices must be integers or slices, not list

In [8]:
print(y[[0,2]])

[2 4]


In [9]:
print(y[y>3])

[4 6]


In [10]:
print(x*5)

[2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6]


In [11]:
print(y*5)

[10 15 20 30]


In [12]:
print(x**2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [13]:
print(y**2)

[ 4  9 16 36]


In [14]:
matrix=[[1,2,4],[3,1,0]]

In [15]:
matrix

[[1, 2, 4], [3, 1, 0]]

In [16]:
type(matrix)

list

In [17]:
print(matrix)

[[1, 2, 4], [3, 1, 0]]


In [18]:
nd_array=np.array(matrix)

In [19]:
print(matrix[1][2])

0


In [20]:
print(nd_array[1,2])

0


In [21]:
np.random.rand() #случайное число из равномерного распределения

0.6443892381732357

In [22]:
np.random.randn() #случайное число из нормального распределения

-0.2375277252951072

In [23]:
np.random.randn(4) #сгенерируем несколько чисел

array([-0.27978192,  0.04355809, -0.03141445,  0.2673977 ])

In [24]:
np.random.randn(4,5) #сгенерируем матрицу

array([[ 0.04597484, -0.80454063, -0.69095963,  0.21614028,  1.84156468],
       [ 0.4693548 ,  0.3567697 , -0.07160638,  0.32211062,  0.35078283],
       [ 1.45427829,  1.03915092, -0.28250463, -0.48285383,  0.83387694],
       [ 1.22567137,  0.06757181, -1.34221238,  1.12014735,  0.14463844]])

In [25]:
print(range(0,8,0.1)) # у стандартной функции range() должен быть целочисленный шаг

TypeError: 'float' object cannot be interpreted as an integer

In [26]:
print(range(0,8,2))

range(0, 8, 2)


In [27]:
print(np.arange(0,8,0.1)) #из пакета numpy

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3  1.4
  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9
  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1  4.2  4.3  4.4
  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5  5.6  5.7  5.8  5.9
  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9  7.   7.1  7.2  7.3  7.4
  7.5  7.6  7.7  7.8  7.9]


In [28]:
%timeit(range(10000))
%timeit(np.arange(10000))

1000000 loops, best of 3: 1.13 µs per loop
The slowest run took 14.03 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 38.5 µs per loop


##  SciPy 

### оптимизация

In [29]:
from scipy import optimize

In [30]:
def f(x):
    return (x[0]-3.2)